server:
  port: ${SPRINGBOOT_PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.jdbc.bind: TRACE



spring:
  security:
    oauth2:
      client:
        provider:
            kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub
        registration:
            kakao:
                client-id: ${KAKAO_CLIENT_ID}
                client-secret: ${KAKAO_CLIENT_SECRET}
                client-authentication-method: client_secret_post
                redirect-uri: ${KAKAO_REDIRECT_URI}
                authorization-grant-type: authorization_code
                client-name: kakao
                scope:
                    - profile_nickname
                    - profile_image
                    - account_email
            google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                redirect-uri: ${GOOGLE_REDIRECT_URI}
                authorization-grant-type: authorization_code
                client-name: google
                scope:
                    - profile
                    - email
  datasource:
    url: jdbc:mysql://${host:localhost}:${DB_PORT:3306}/${database:innerview}
    username: ${username:root}
    password: ${password:pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate


kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

uploads:
  path: ${UPLOAD_PATH:uploads}

jwt:
  secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef}
  expiration: ${JWT_EXPIRATION:3600000}

file:
  video-path: classpath:/static/videos/
  server-path: https://server.chani.pro/api/video/

---
spring:
  config:
    activate:
      on-profile: build
server:
  port: ${SPRINGBOOT_PORT_SERVICE:8080}

